# Use the desired Python version
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy application files to the container
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set the entry point for the container
CMD ["python", "main.py"]
